@startuml
!pragma teoz true
box "Terminal Process"
participant bash

box "AcquisitionManager" #F3E5F5
participant "Main" as main
participant "AcquisitionManager" as AcqManager
participant "producer[i]:pthread_t" as producer
participant "mutex_write:pthread_mutex_t" as mutex_write
participant "mutex_index:pthread_mutex_t" as mutex_index
participant "sem_empty:sem(255)" as sem_empty
participant "sem_full:sem(0)" as sem_full
participant "index:int" as index
participant "buffer_index:int" as buffer_index
participant "buffer_data:MSG_BLOCK" as buffer_data
end box

box "MessageAdder" #B2DFDB
participant "consumer:pthread_t" as consumer
participant "messageAdder" as messageAdder
participant "mutex_msg:mutex_t" as mutex_msg
participant "sum:MSG_BLOCK" as sum
end box

box "DisplayManager" #FFCCBC
participant "display:pthread_t" as display
participant "displayManager" as displayManager
end box
end box

activate bash
bash -> main: ./AcquisitionManager
activate main

main->AcqManager: AcquisitionManagerInit
activate AcqManager

AcqManager-> buffer_data: create buffer
activate buffer_data
return

AcqManager-> producer: pthread_create
activate producer #FFBBBB

producer -> AcqManager: writeMessage
note over AcqManager : Writing message

AcqManager -> sem_empty : sem_wait
activate sem_empty
return

AcqManager -> mutex_write : pthread_mutex_lock
activate mutex_write
return

AcqManager -> index: Get and increment
activate index
return

AcqManager -> mutex_write : pthread_mutex_unlock
activate mutex_write
return

AcqManager -> buffer_data : Write data
activate buffer_data
return

AcqManager -> mutex_index : pthread_mutex_lock
activate mutex_index
return

AcqManager -> buffer_index : Store index
activate buffer_index
return

AcqManager -> mutex_index : pthread_mutex_unlock
activate mutex_index
return

AcqManager -> sem_full: sem_post
activate sem_full
return

AcqManager -> producer: return
deactivate producer

bash -> messageAdder: ./MessageAdder
activate messageAdder

messageAdder -> consumer: pthread_create
activate consumer #FFBBBB

consumer -> AcqManager: getMessage
note over AcqManager: Retrieving message

AcqManager -> sem_full: sem_wait
activate sem_full
return

AcqManager -> index: Read index
activate index
return

AcqManager -> buffer_index: Read buffer index
activate buffer_index
return

AcqManager -> buffer_data: Read message
activate buffer_data
return

AcqManager -> sem_empty: sem_post
activate sem_empty
return

AcqManager -> messageAdder: notifyMessageRetrieved
note over messageAdder: Message successfully retrieved

consumer -> messageAdder: Store message

messageAdder -> mutex_msg: pthread_mutex_lock
activate mutex_msg
return

messageAdder -> sum: Add message
activate sum
return

messageAdder -> mutex_msg: pthread_mutex_unlock
activate mutex_msg
return

consumer -> messageAdder: pthread_exit
deactivate consumer

bash -> displayManager: ./DisplayManager
activate displayManager

displayManager -> display: pthread_create
activate display #FFBBBB

display -> messageAdder: getCurrentSum
activate messageAdder

messageAdder -> mutex_msg: pthread_mutex_lock
activate mutex_msg
return

messageAdder -> sum: Read messages
activate sum
return

messageAdder -> mutex_msg: pthread_mutex_unlock
activate mutex_msg
return

messageAdder -> display: Return data
deactivate messageAdder

display -> displayManager: pthread_exit
deactivate display

displayManager -> bash: End DisplayManager
deactivate displayManager

AcqManager -> main: End AcquisitionManager
deactivate AcqManager

main -> bash: End program
deactivate main

@enduml